"""
3DN Scraper Template - Base Configuration
Version: 1.0.0

DO NOT EDIT THIS FILE
Override settings in client-specific configuration files

This file defines default settings that apply to all client deployments.
Client deployments inherit these defaults and override as needed.
"""

from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime


class BaseConfig:
    """Base configuration class for 3DN Scraper Template
    
    All client configurations should inherit from this class and
    override only the settings that need to be customized.
    """
    
    # 3DN Template Information
    TEMPLATE_VERSION = "1.0.0"
    TEMPLATE_NAME = "3DN Scraper Template"
    
    # Client Information (must be overridden in client config)
    CLIENT_NAME = "base"
    CLIENT_FULL_NAME = "Base Configuration"
    
    # Website Configuration (must be overridden in client config)
    BASE_URL = "https://example.com"
    
    # URL Patterns (should be overridden in client config)
    CATEGORY_URL_PATTERN = "/category/{slug}/"
    PRODUCT_URL_PATTERN = "/product/{slug}/"
    
    # Output Configuration (should be overridden in client config)
    OUTPUT_PREFIX = "Scrape"
    BASE_OUTPUT_DIR = "scrapes"
    
    # Directory structure (applies to all clients)
    SUBDIRS = [
        "categories",
        "products", 
        "screenshots",
        "logs",
        "reports",
        "pdfs",
        "PDFs"
    ]
    
    # Timeouts (milliseconds) - can be overridden per client
    PAGE_TIMEOUT = 60000  # 60 seconds for page load
    DETAIL_PAGE_TIMEOUT = 35000  # 35 seconds for product detail pages
    PDF_TIMEOUT = 30000  # 30 seconds for PDF downloads
    
    # Rate Limiting (seconds) - can be overridden per client
    RATE_LIMIT_MIN = 1.0  # Minimum seconds between requests
    RATE_LIMIT_MAX = 3.0  # Maximum seconds between requests
    RATE_LIMIT_DELAY = 2  # Deprecated - use RATE_LIMIT_MIN/MAX instead
    
    # Test Mode Settings - can be overridden per client
    TEST_CATEGORY_LIMIT = 2  # Number of categories in test mode
    TEST_PRODUCT_LIMIT = 5  # Number of products per category in test mode
    
    # User Agent - can be overridden per client
    USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    
    # Retry Configuration - can be overridden per client
    MAX_RETRIES = 3  # Maximum retry attempts for failed requests
    RETRY_DELAY = 5  # Seconds between retry attempts
    
    # Screenshot Settings - can be overridden per client
    SCREENSHOT_ENABLED = True
    SCREENSHOT_WIDTH = 1920
    SCREENSHOT_HEIGHT = 1080
    
    # PDF Download Settings - can be overridden per client
    PDF_MAX_RETRIES = 3
    
    # Known Categories (fallback) - should be overridden in client config
    KNOWN_CATEGORIES = []
    
    # PDF Configuration - should be overridden in client config
    HAS_SDS_DOCUMENTS = False
    HAS_PDS_DOCUMENTS = False
    SDS_FIELD_NAME = "sds_url"
    PDS_FIELD_NAME = "pds_url"
    
    # Product Schema Mapping - should be overridden in client config
    PRODUCT_SCHEMA = {
        "name_field": "product_name",
        "url_field": "product_url",
        "image_field": "product_image_url",
        "overview_field": "product_overview",
        "description_field": "product_description",
        "sku_field": "product_skus",
        "categories_field": "product_categories"
    }
    
    @classmethod
    def create_run_directory(cls, test_mode: bool = False) -> Path:
        """Create a timestamped run directory for this client deployment
        
        Args:
            test_mode: If True, adds "_TEST" suffix to directory name
            
        Returns:
            Path object for the run directory
        """
        base_path = Path(cls.BASE_OUTPUT_DIR)
        base_path.mkdir(exist_ok=True)
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_name = f"{cls.OUTPUT_PREFIX}_{timestamp}"
        if test_mode:
            run_name += "_TEST"
        
        run_dir = base_path / run_name
        run_dir.mkdir(exist_ok=True)
        
        # Create subdirectories
        for subdir in cls.SUBDIRS:
            (run_dir / subdir).mkdir(exist_ok=True)
        
        return run_dir
    
    @classmethod
    def get_category_dir(cls, run_dir: Path, category_slug: str) -> Path:
        """Get or create category directory
        
        Args:
            run_dir: The run directory
            category_slug: The category slug
            
        Returns:
            Path object for the category directory
        """
        category_dir = run_dir / "categories" / category_slug
        category_dir.mkdir(exist_ok=True, parents=True)
        return category_dir
    
    @classmethod
    def get_category_url(cls, category_slug: str) -> str:
        """Build category URL from slug
        
        Args:
            category_slug: The category slug
            
        Returns:
            Full URL for the category
        """
        pattern = cls.CATEGORY_URL_PATTERN.replace("{slug}", category_slug)
        return cls.BASE_URL + pattern
    
    @classmethod
    def get_product_url(cls, product_slug: str) -> str:
        """Build product URL from slug
        
        Args:
            product_slug: The product slug
            
        Returns:
            Full URL for the product
        """
        pattern = cls.PRODUCT_URL_PATTERN.replace("{slug}", product_slug)
        return cls.BASE_URL + pattern
    
    @classmethod
    def get_config_summary(cls) -> Dict:
        """Get a summary of the current configuration
        
        Returns:
            Dictionary with key configuration settings
        """
        return {
            "template_version": cls.TEMPLATE_VERSION,
            "client_name": cls.CLIENT_NAME,
            "client_full_name": cls.CLIENT_FULL_NAME,
            "base_url": cls.BASE_URL,
            "output_dir": cls.BASE_OUTPUT_DIR,
            "has_sds": cls.HAS_SDS_DOCUMENTS,
            "has_pds": cls.HAS_PDS_DOCUMENTS,
            "known_categories_count": len(cls.KNOWN_CATEGORIES)
        }
